openapi: 3.1.1
info:
  title: Findymail API documentation
  description: >-
    This documentation aims to provide all the information you need to work with
    our API.


    <b>Rate limit</b>: all endpoints have a concurrent rate limit of 300
    simultaneous requests, unless stated otherwise.
  version: 1.0.0
servers:
  - url: https://app.findymail.com
paths:
  /api/verify:
    post:
      summary: Verify an email for potential bounce
      operationId: verifyAnEmailForPotentialBounce
      description: Uses one verifier credit on all attempted verification
      parameters: []
      responses:
        "200":
          description: ""
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - "{ \"email\": \"john@example.com\", \"verified\" : true,
                    \"provider\": 'Google'}"
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Email Verifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email to verify
                  nullable: false
                  examples:
                    - jannie.reinger@example.com
              required:
                - email
  /api/lists:
    get:
      summary: Get the list of contact lists
      operationId: getTheListOfContactLists
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  lists:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          examples:
                            - 1
                        name:
                          type: string
                          examples:
                            - my list
                        created_at:
                          type: string
                          examples:
                            - 2022-08-23T16:46:43.000000Z
                        updated_at:
                          type: string
                          examples:
                            - 2022-08-23T16:46:43.000000Z
                        shared_with_team:
                          type: boolean
                          examples:
                            - false
                        is_owner:
                          type: boolean
                          examples:
                            - true
                    examples:
                      - - id: 1
                          name: my list
                          created_at: 2022-08-23T16:46:43.000000Z
                          updated_at: 2022-08-23T16:46:43.000000Z
                          shared_with_team: false
                          is_owner: true
                examples:
                  - lists:
                      - id: 1
                        name: my list
                        created_at: 2022-08-23T16:46:43.000000Z
                        updated_at: 2022-08-23T16:46:43.000000Z
                        shared_with_team: false
                        is_owner: true
      tags:
        - Contacts
    post:
      summary: Create a new list
      operationId: createANewList
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: object
                    properties:
                      id:
                        type: integer
                        examples:
                          - 1
                      name:
                        type: string
                        examples:
                          - new list
                      created_at:
                        type: string
                        examples:
                          - 2022-08-23T16:46:43.000000Z
                      updated_at:
                        type: string
                        examples:
                          - 2022-08-23T16:46:43.000000Z
                      shared_with_team:
                        type: boolean
                        examples:
                          - false
                      is_owner:
                        type: boolean
                        examples:
                          - true
                examples:
                  - list:
                      id: 1
                      name: new list
                      created_at: 2022-08-23T16:46:43.000000Z
                      updated_at: 2022-08-23T16:46:43.000000Z
                      shared_with_team: false
                      is_owner: true
      tags:
        - Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the list
                  nullable: false
                  examples:
                    - nam
              required:
                - name
  /api/lists/{id}:
    put:
      summary: Update a contact list
      operationId: updateAContactList
      description: ""
      parameters: []
      responses: {}
      tags:
        - Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name of the list
                  nullable: false
                  examples:
                    - adipisci
                isShared:
                  type: boolean
                  description: Enable/disable list sharing with the team
                  nullable: false
                  examples:
                    - false
              required:
                - name
                - isShared
    delete:
      summary: Delete a given list
      operationId: deleteAGivenList
      description: ""
      parameters: []
      responses: {}
      tags:
        - Contacts
    parameters:
      - in: path
        name: id
        description: The ID of the list.
        required: true
        schema:
          type: integer
        examples:
          default:
            value: 53
  /api/contacts/get/{id}:
    get:
      summary: Get contacts saved
      operationId: getContactsSaved
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - >-
                    {
                          "draw": 0,
                          "recordsTotal": 1,
                          "recordsFiltered": 1,
                          "data": [
                              {
                                  "id": 1,
                                  "name": "John Doe",
                                  "email": "john@company.com",
                                  "linkedin_url": "https://linkedin.com/in/linkedin",
                                  "company": "MyCompany",
                                  "job_title": "CEO"
                              },
                          ],
                    }
      tags:
        - Contacts
    parameters:
      - in: path
        name: id
        description: Optional parameter. Get contacts from a specified list. If 0, no
          list used ("All contacts").
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: When the value is omitted
            value: ""
          present:
            summary: When the value is present
            value: 1
  /api/search/name:
    post:
      summary: Find from name
      operationId: findFromName
      description: Find someone's email from name and website. Uses one finder credit
        if a verified email is found.
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                oneOf:
                  - description: Success
                    type: object
                    properties:
                      contact:
                        type: object
                        properties:
                          name:
                            type: string
                            examples:
                              - John Doe
                          domain:
                            type: string
                            examples:
                              - website.com
                          email:
                            type: string
                            examples:
                              - john@website.com
                    examples:
                      - contact:
                          name: John Doe
                          domain: website.com
                          email: john@website.com
                  - description: Webhook URL provided process asynchronous
                    type: object
                    properties:
                      payload:
                        type: object
                        properties:
                          contact:
                            type: object
                            properties:
                              name:
                                type: string
                                examples:
                                  - john doe
                              email:
                                type: string
                                examples:
                                  - email@website.com
                              domain:
                                type: string
                                examples:
                                  - website.com
                        description: (when using webhook_url) object POST method callback request
                          triggered when webhook_url provided. See example
                          response
                    examples:
                      - payload:
                          contact:
                            name: john doe
                            email: email@website.com
                            domain: website.com
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Email Finder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Person's full name
                  nullable: false
                  examples:
                    - John Doe
                domain:
                  type: string
                  description: Email domain (best) or company name
                  nullable: false
                  examples:
                    - website.com
                webhook_url:
                  type: string
                  description: Webhook URL that will receive the result as callback. If submitted,
                    email search will happen in the background and notify this
                    URL upon completion.
                  nullable: false
                  examples:
                    - null
              required:
                - name
                - domain
  /api/search/domain:
    post:
      summary: Find from domain
      operationId: findFromDomain
      description: >-
        Try finding a contact with a valid email at a given domain with a given
        role.

        A contact is only returned if we found a valid email.


        Due to the heavy processing involved (real-time search), this endpoint
        is limited to 5 concurrent requests (when used synchronously)

        and async jobs can take up to 24 hours to be processed depending on our
        workload (usually sooner).
      parameters: []
      responses:
        "0":
          description: Webhook URL provided process asynchronous
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      contacts:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              examples:
                                - say my name
                            email:
                              type: string
                              examples:
                                - email@findymail.com
                            domain:
                              type: string
                              examples:
                                - domain.com
                        examples:
                          - - name: say my name
                              email: email@findymail.com
                              domain: domain.com
                    description: (when using webhook_url) object POST method callback request
                      triggered when webhook_url provided. See example response
                examples:
                  - payload:
                      contacts:
                        - name: say my name
                          email: email@findymail.com
                          domain: domain.com
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      type: object
                      properties:
                        domain:
                          type: string
                          examples:
                            - website.com
                        email:
                          type: string
                          examples:
                            - john@website.com
                        name:
                          type: string
                          examples:
                            - john doe
                    examples:
                      - - domain: website.com
                          email: john@website.com
                          name: john doe
                examples:
                  - contacts:
                      - domain: website.com
                        email: john@website.com
                        name: john doe
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Email Finder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                  description: Email domain
                  nullable: false
                  examples:
                    - domain.com
                roles:
                  type: array
                  description: Target roles related to the given domain (max 3 roles)
                  items:
                    type: string
                  examples:
                    - - CEO
                      - Founder
                webhook_url:
                  type: string
                  description: Webhook URL that will receive the result as callback. If submitted,
                    search will happen in the background and notify this URL
                    upon completion.
                  nullable: false
                  examples:
                    - http://www.hegmann.com/nobis-omnis-consequatur-quis-labore-labore-pariatur.html
              required:
                - domain
                - roles
  /api/search/linkedin:
    post:
      summary: Find from Linkedin
      operationId: findFromLinkedin
      description: >-
        Find someone's email from a Linkedin URL. Uses one finder credit if a
        verified email is found.


        This endpoint is limited to 30 concurrent requests (when used
        synchronously)
      parameters: []
      responses:
        "0":
          description: Webhook URL provided process asynchronous
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      contact:
                        type: object
                        properties:
                          name:
                            type: string
                            examples:
                              - john doe
                          email:
                            type: string
                            examples:
                              - email@website.com
                          domain:
                            type: string
                            examples:
                              - website.com
                    description: (when using webhook_url) object POST method callback request
                      triggered when webhook_url provided. See example response
                examples:
                  - payload:
                      contact:
                        name: john doe
                        email: email@website.com
                        domain: website.com
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  contact:
                    type: object
                    properties:
                      name:
                        type: string
                        examples:
                          - John Doe
                      domain:
                        type: string
                        examples:
                          - website.com
                      email:
                        type: string
                        examples:
                          - john@website.com
                examples:
                  - contact:
                      name: John Doe
                      domain: website.com
                      email: john@website.com
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Email Finder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                linkedin_url:
                  type: string
                  description: Person's Linkedin URL. (can be full URL
                    "https://linkedin.com/in/johndoe" or username only
                    "johndoe")
                  nullable: false
                  examples:
                    - https://linkedin.com/in/johndoe
                webhook_url:
                  type: string
                  description: Webhook URL that will receive the result as callback. If submitted,
                    email search will happen in the background and notify this
                    URL upon completion.
                  nullable: false
                  examples:
                    - null
              required:
                - linkedin_url
  /api/linkedin/profile:
    post:
      summary: Get Linkedin Profile
      operationId: getLinkedinProfile
      description: >-
        Get information from a Linkedin profile.


        This endpoint uses 1 credit per request (warning: this uses a credit
        even if the profile does not exist. Please make sure the input is
        correct)


        This endpoint does NOT return an email.

        To find email from a Linkedin profile, please use "Email Finder > Find
        from Linkedin" instead.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  linkedInId:
                    type: string
                    examples:
                      - "123"
                  fullName:
                    type: string
                    examples:
                      - John Doe
                  username:
                    type: string
                    examples:
                      - johndoe
                  headline:
                    type: string
                    examples:
                      - CEO at Example
                  jobTitle:
                    type: string
                    examples:
                      - CEO
                  summary:
                    type: string
                    examples:
                      - Summary
                  city:
                    type: string
                    examples:
                      - City
                  region:
                    type: string
                    examples:
                      - Region
                  country:
                    type: string
                    examples:
                      - Country
                  companyLinkedinUrl:
                    type: string
                    examples:
                      - https://linkedin.com/company/example
                  companyName:
                    type: string
                    examples:
                      - Example
                  companyWebsite:
                    type: string
                    examples:
                      - example.com
                  isPremium:
                    type: boolean
                    examples:
                      - true
                  isOpenProfile:
                    type: boolean
                    examples:
                      - true
                  skills:
                    type: array
                    examples:
                      - []
                  jobs:
                    type: array
                    items:
                      type: object
                      properties:
                        jobTitle:
                          type: string
                          examples:
                            - CEO
                        companyName:
                          type: string
                          examples:
                            - Example
                        companyWebsite:
                          type: string
                          examples:
                            - https://linkedin.com/company/example
                        jobDescription:
                          type: string
                          examples:
                            - Description
                        startDate:
                          type: string
                          examples:
                            - 2020-01-01
                        endDate:
                          type: string
                          examples:
                            - ""
                    examples:
                      - - jobTitle: CEO
                          companyName: Example
                          companyWebsite: https://linkedin.com/company/example
                          jobDescription: Description
                          startDate: 2020-01-01
                          endDate: ""
                        - jobTitle: CTO
                          companyName: Example
                          companyWebsite: https://linkedin.com/company/example
                          jobDescription: Description
                          startDate: 2020-01-01
                          endDate: 2021-01-01
                examples:
                  - linkedInId: "123"
                    fullName: John Doe
                    username: johndoe
                    headline: CEO at Example
                    jobTitle: CEO
                    summary: Summary
                    city: City
                    region: Region
                    country: Country
                    companyLinkedinUrl: https://linkedin.com/company/example
                    companyName: Example
                    companyWebsite: example.com
                    isPremium: true
                    isOpenProfile: true
                    skills: []
                    jobs:
                      - jobTitle: CEO
                        companyName: Example
                        companyWebsite: https://linkedin.com/company/example
                        jobDescription: Description
                        startDate: 2020-01-01
                        endDate: ""
                      - jobTitle: CTO
                        companyName: Example
                        companyWebsite: https://linkedin.com/company/example
                        jobDescription: Description
                        startDate: 2020-01-01
                        endDate: 2021-01-01
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Misc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                linkedin_url:
                  type: string
                  description: Person's Linkedin URL. (can be full URL
                    "https://linkedin.com/in/johndoe" or username only
                    "johndoe")
                  nullable: false
                  examples:
                    - https://linkedin.com/in/johndoe
              required:
                - linkedin_url
  /api/search/employees:
    post:
      summary: Find Employees
      operationId: findEmployees
      description: |-
        Find one or more employees using the company website and job title.

        This endpoint uses 1 credit per found contact.

        This endpoint does NOT return an email.
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                examples:
                  - - name: John Done
                      linkedinUrl: https://www.linkedin.com/in/john-doe/
                      companyWebsite: https://www.findymail.com
                      companyName: Findymail
                      jobTitle: Software Engineer
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Misc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                website:
                  type: string
                  description: company website
                  nullable: false
                  examples:
                    - google.com
                job_titles:
                  type: array
                  description: target job titles (max 10)
                  items:
                    type: string
                  examples:
                    - - Software Engineer
                      - CEO
                count:
                  type: integer
                  description: Number of contacts to return (max 5). Default 1.
                  nullable: false
                  examples:
                    - 2
              required:
                - website
                - job_titles
  /api/search/phone:
    post:
      summary: Find phone
      operationId: findPhone
      description: >-
        Find someone's phone number from a Linkedin URL. Uses 10 finder credits
        if a phone is found.


        For legal reasons, requests for EU citizens will not return any result.
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  phone:
                    type: string
                    examples:
                      - "+1234567890"
                examples:
                  - phone: "+1234567890"
        "402":
          description: "Error : Not enough credits"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Not enough credits
                examples:
                  - error: Not enough credits
        "423":
          description: "Error : Subscription is paused"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      - Subscription is paused
                examples:
                  - error: Subscription is paused
      tags:
        - Phone Finder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                linkedin_url:
                  type: string
                  description: Person's Linkedin URL. (can be full URL
                    "https://linkedin.com/in/johndoe" or username only
                    "johndoe")
                  nullable: false
                  examples:
                    - https://linkedin.com/in/johndoe
              required:
                - linkedin_url
  /api/credits:
    get:
      summary: Get remaining credits
      operationId: getRemainingCredits
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  credits:
                    type: integer
                    examples:
                      - 150
                  verifier_credits:
                    type: integer
                    examples:
                      - 100
                examples:
                  - credits: 150
                    verifier_credits: 100
      tags:
        - User
tags:
  - name: Email Verifier
    description: ""
  - name: Contacts
    description: ""
  - name: Email Finder
    description: ""
  - name: Misc
    description: ""
  - name: Phone Finder
    description: ""
  - name: User
    description: ""
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: You can retrieve your token by visiting <a
        href="/user/api-tokens">API page</a>.
security:
  - default: []
